name: Update streams
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v2

      - name: update streams
        run: sh BIG_BROTHER_PORTUGAL_LIVE.sh

      - name: setup git config
        run: |
          git config user.name "M3UPT Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git pull
          git add BIG_BROTHER_PORTUGAL_LIVE.M3U8
          git commit -m "Update streams"
          git push origin main
