name: Extrair informações de vídeo usando yt-dlp

on:
  push:
    branches:
      - main

jobs:
  extract_info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install yt-dlp

      - name: Extrair informações de vídeo
        run: |
          title=$(yt-dlp --get-title https://www.bilibili.com/video/BV1nS4y1N7Fm/?spm_id_from=333.337.search-card.all.click | sed 's/\&/\&amp;/g')
          duration=$(yt-dlp --get-duration https://www.bilibili.com/video/BV1nS4y1N7Fm/?spm_id_from=333.337.search-card.all.click | awk '{printf "%.0f",$1}')
          url=$(yt-dlp --get-url https://www.bilibili.com/video/BV1nS4y1N7Fm/?spm_id_from=333.337.search-card.all.click)
          echo "#EXTM3U" > playlist.m3u
          echo "#EXTINF:$duration tvg-id=\"Bilibili\" tvg-name=\"Bilibili\" tvg-logo=\"https://i0.hdslb.com/bfs/vc/1f7d98d94ee4b40842c21d2f425a8f90a9619f12.png\" group-title=\"Bilibili\",$title" >> playlist.m3u
          echo $url >> playlist.m3u

      - name: Salvar arquivo .m3u
        uses: actions/upload-artifact@v2
        with:
          name: playlist
          path: playlist.m3u
