name: ANGOLA EN DIRECTO


on:
  schedule:
    - cron: '0 9 * * *' # 6 AM Argentina Time (Buenos Aires) is 9 AM UTC
  workflow_dispatch: {}

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium bs4 yt-dlp streamlink



    - name: Run Python script
      run: python youtubeplay3.py

    - name: Commit and push changes
      run: |
        git config user.name "Your Name"
        git config user.email "your.email@example.com"
        git add TPAANGOLA.m3u8
        git commit -m "Update TPAANGOLA.m3u8"
        git push
