name: Update streams

on:
  schedule:
    - cron: "0 */2 * * *"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: update streams
        run: sh TVIREALITY.M3U8.sh

      - name: setup git config
        run: |
          git config --global user.name "M3UPT Bot"
          git config --global user.email "<>"

      - name: commit
        run: |
          git pull
          git add TVIREALITY.M3U8
          git commit -m "Update streams"
          git push origin main
